### PR TITLE
FIx for CURA for avoiding parser error

### PR DESCRIPTION
**Pull request by nopp**
avoiding Error on 'M140 S': unable to parse.

### CODE REVIEW

**Comment by stvptrsn** [comment]
Sorry, this repo is only intended to be for sharing what I use.  If you have a concern about anything I'm sharing please open an issue instead of pull request.

**Comment by nopp** [comment]
ok.

**Comment by stvptrsn** [comment]
I appreciate it, just not the intent of this repo.  I may rethink how I run this though.  I would prefer issue reports though

**Comment by stvptrsn** [comment]
I corrected the issue.  Since the intent is to share what I use, I removed the print start/end code altogether since I don't use it.  Thanks again for bringing this to my attention, I will be trying to remember this type of thing for future uploads.

**Pull request closed without merging**
